### ISSUE TITLE
The types field value can not be null.

### ISSUE THREAD

**Issue by styrken** [virtualshield/rails-graphql#31]
Running the following Introspection query fails with "The types field vlaue can not be null". This used to work in an earlier version. 

```
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by crashtech** [comment]
The gem hasn't changed in a while. It seems that it is related to your setup. Can you try it isolated, outside of the application?

**Comment by styrken** [comment]
Maybe. But we did not run this query since we used the beta gem

**Comment by crashtech** [comment]
This is a core query, and there are tests for it. It works correctly, so definitely not something with the gem itself. Seems to be something with your env.

**Comment by styrken** [comment]
Can we set up a session to debug this?

**Comment by crashtech** [comment]
The tests are all passing, which includes a test for this query. So before, please test it isolated, without your application environment.
https://github.com/virtualshield/rails-graphql/blob/master/test/assets/introspection.gql
https://github.com/virtualshield/rails-graphql/blob/master/test/integration/memory/star_wars_introspection_test.rb#L134
