### ISSUE TITLE
Undefined behavior?

### ISSUE THREAD

**Issue by borela** [virtualshield/rails-graphql#34]
In this [loop](https://github.com/virtualshield/rails-graphql/blob/master/ext/shared.c#L75) it is expecting the array to end with a null byte, but, at this [point](https://github.com/virtualshield/rails-graphql/blob/master/ext/gql_parser.c#L86C62-L86C62) it passes the [GQL_EXECUTION_KEYWORDS](https://github.com/virtualshield/rails-graphql/blob/master/ext/shared.c#L10) which doesn't look like it is null-terminated. The code is working, is the compiler adding the null byte automatically?

**Comment by crashtech** [comment]
Interesting point. I might be doing that loop wrongly. I'll attempt a fix with a for loop.

**Comment by crashtech** [comment]
There will be a release with this fix.
