### ISSUE TITLE
FieldSet & QuerySet are broken

### ISSUE THREAD

**Issue by jhass** [virtualshield/rails-graphql#35]
In https://github.com/virtualshield/rails-graphql/blob/master/lib/rails/graphql/alternative/field_set.rb the references to `Field` resolve to `Rails::GraphQL::Alternative::Field` rather than `Rails::GrahQL::Field` and thus the resolution of `OutputField`, `MutationField` and `SubscriptionField` fail.

Additionally there's a missing autoload for `Rails::GraphQL::Alternative::QuerySet`.

Finally even with the above two points fixed I can't get the shortcuts at `Rails::GraphQL::FieldSet` nor `Rails::GraphQL::QuerySet` to work.

**Comment by crashtech** [comment]
It should be fixed on this last release. Please make sure to import the alternatives properly.
