### ISSUE TITLE
RubyGems home page of this gem is 404

### ISSUE THREAD

**Issue by mensfeld** [virtualshield/rails-graphql#7]
Hey there,

Just wanted to bring to your attention, that your project website from here https://rubygems.org/gems/rails-graphql is just 404 (https://virtualshield.com/rails-graphql).

Ah and the last RG release is not here: https://github.com/virtualshield/rails-graphql/releases

Have a great day :)

**Comment by crashtech** [comment]
Hi There!

Thanks for the notes! This gem is still in its very early stages. We plan to release a dedicated web page (https://virtualshield.com/rails-graphql) explaining all about it and the releases will get on track when it gets more stable.
