### ISSUE TITLE
Wiki inaccessible

### ISSUE THREAD

**Issue by brittlewis12** [virtualshield/rails-graphql#9]
Hello!

I'm exploring this library and noticed that the [wiki link](https://github.com/virtualshield/rails-graphql/wiki) redirects back to the project root here on github.

Is there any content there? If so, would you all be open to expanding access to the wiki? Would appreciate it!

**Comment by crashtech** [comment]
Hello @brittlewis12! Thanks for reaching out. We don't have a wiki page for this gem yet. Documentation will be properly added after it goes to a production project and we do the first round of fixes/adjustments. Let me know If I can help in any other way.

**Comment by brittlewis12** [comment]
I see, thank you for such a prompt response! 

i might recommend removing the wiki link from the readme to avoid any further confusion to this effect in the meantime.

best of luck with the library, thanks so much for your efforts here!
